image:
  file: .gitpod.Dockerfile

tasks:
  - name: App
    init: |
      ./build.sh
    command: |
      export PATH="$PATH:/$(pwd)/scripts"
      ./run.sh

ports:
  - name: App
    port: 3000
    onOpen: open-preview
