image:
  file: .gitpod/Dockerfile
  context: .gitpod
workspaceLocation: multirepo-yalc/.gitpod/ws-default.code-workspace

tasks:
  - name: App
    init: |
      ./build.sh
    command: |
      cd app
      node server.js

  - name: Workspace-Mounts
    command: |
      ws-sync.sh --interval 10

ports:
  - name: App
    port: 3000
    onOpen: open-preview
