image:
  file: .gitpod/.gitpod.Dockerfile
  context: .gitpod
workspaceLocation: multirepo-yalc/.gitpod/ws-default.code-workspace

tasks:
  - name: App
    init: |
      ./build.sh
    command: |
      node server.js

  - name: Terminal
    command: |
      echo "Hello! Run `ws-sync.sh` to mount other running workspaces into this workspace."

ports:
  - name: App
    port: 3000
    onOpen: open-preview
