image:
  file: .gitpod/.gitpod.Dockerfile
  context: .gitpod
workspaceLocation: monorepo_slicing/.gitpod/ws-default.code-workspace

tasks:
  - name: App
    init: |
      ./build.sh
    command: |
      node server.js

  - name: Terminal
    command: |
      read -p "To access other workspaces, please create a token at $GITPOD_HOST/user/tokens and enter it here: " GITPOD_TOKEN
      gitpod login --token "$GITPOD_TOKEN"

ports:
  - name: App
    port: 3000
    onOpen: open-preview
