image:
  file: .gitpod/.gitpod.Dockerfile
  context: .gitpod

tasks:
  - name: App
    init: |
      ./build.sh
    command: |
      node server.js

  - name: Terminal
    command: |
      ls -l scripts/

ports:
  - name: App
    port: 3000
    onOpen: open-preview
